### PR TITLE
Symfony 4 support

### LINKED ISSUE #98: Symfony 4.0
It is planned some update to support the Sf4?

Thanks,

Paulo Dias

### PR DESCRIPTION
**Pull request by Nyholm**
Adding symfony 4 support an a new fancy travis.yml file to prove it. 

I also added some smoke test for the bundle

This PR will fix #98 and replace #96. 

I hope this could be quickly reviewed and released.

### CODE REVIEW

**Comment by marcaube** [comment]
Thanks @Nyholm, much appreciated 👍 Love the podcast BTW

**Comment by Nyholm** [comment]
Thank you. 

I'm just done with this PR. I think you need to restart [this build](https://travis-ci.org/marcaube/ObHighchartsBundle/jobs/322188131) and everything will be green

**Comment by Nyholm** [comment]
Excellent. Thank you!

**Comment by Nyholm** [comment]
Could I bother you with tagging 1.6?

**Comment by marcaube** [comment]
@Nyholm done

**Pull request merged**
